
CREATE TABLE BARANG (
	KODEBRG int NOT NULL,
	NAMABRG varchar(255) NOT NULL
);

INSERT INTO BARANG (KODEBRG, NAMABRG) VALUES (1, 'MEJA');
INSERT INTO BARANG (KODEBRG, NAMABRG) VALUES (2, 'KURSI');
INSERT INTO BARANG (KODEBRG, NAMABRG) VALUES (3, 'LAMPU');

CREATE TABLE JUAL (
	KODEBRG int NOT NULL,
	JUMLAH int NOT NULL
);

INSERT INTO JUAL (KODEBRG, JUMLAH) VALUES (1, 2);
INSERT INTO JUAL (KODEBRG, JUMLAH) VALUES (1, 3);
INSERT INTO JUAL (KODEBRG, JUMLAH) VALUES (2, 4);

SELECT * FROM JUAL;

SELECT a.KODEBRG,
a.NAMABRG,
COALESCE(SUM(B.JUMLAH),0) AS JML_JUAL
FROM BARANG a
LEFT JOIN JUAL B
ON a.KODEBRG = b.KODEBRG
GROUP BY a.NAMABRG, a.KODEBRG
ORDER BY a.KODEBRG
ASC;
